# Set the language
language: java

# Set the Java version
jdk:
  - openjdk11

install:
- mvn install -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

notifications:
    email: omoniyi24@gmail.com
    
    
# command for github to recognize ./mvnw is
# git update-index --chmod=+x mvnw


#C:\Program Files (x86)\Common Files\Oracle\Java\javapath

#C:\ProgramData\DockerDesktop\version-bin